// Generated by gencpp from file demo/addTwoNumResponse.msg
// DO NOT EDIT!


#ifndef DEMO_MESSAGE_ADDTWONUMRESPONSE_H
#define DEMO_MESSAGE_ADDTWONUMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo
{
template <class ContainerAllocator>
struct addTwoNumResponse_
{
  typedef addTwoNumResponse_<ContainerAllocator> Type;

  addTwoNumResponse_()
    : sum(0.0)  {
    }
  addTwoNumResponse_(const ContainerAllocator& _alloc)
    : sum(0.0)  {
  (void)_alloc;
    }



   typedef float _sum_type;
  _sum_type sum;




  typedef boost::shared_ptr< ::demo::addTwoNumResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo::addTwoNumResponse_<ContainerAllocator> const> ConstPtr;

}; // struct addTwoNumResponse_

typedef ::demo::addTwoNumResponse_<std::allocator<void> > addTwoNumResponse;

typedef boost::shared_ptr< ::demo::addTwoNumResponse > addTwoNumResponsePtr;
typedef boost::shared_ptr< ::demo::addTwoNumResponse const> addTwoNumResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo::addTwoNumResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo::addTwoNumResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace demo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::demo::addTwoNumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo::addTwoNumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo::addTwoNumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo::addTwoNumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo::addTwoNumResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo::addTwoNumResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo::addTwoNumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f720a7bfc448e377e8e2dd877c1aef43";
  }

  static const char* value(const ::demo::addTwoNumResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf720a7bfc448e377ULL;
  static const uint64_t static_value2 = 0xe8e2dd877c1aef43ULL;
};

template<class ContainerAllocator>
struct DataType< ::demo::addTwoNumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo/addTwoNumResponse";
  }

  static const char* value(const ::demo::addTwoNumResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo::addTwoNumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 sum\n\
\n\
";
  }

  static const char* value(const ::demo::addTwoNumResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo::addTwoNumResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct addTwoNumResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo::addTwoNumResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo::addTwoNumResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<float>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_MESSAGE_ADDTWONUMRESPONSE_H
