// Generated by gencpp from file demo/addTwoNum.msg
// DO NOT EDIT!


#ifndef DEMO_MESSAGE_ADDTWONUM_H
#define DEMO_MESSAGE_ADDTWONUM_H

#include <ros/service_traits.h>


#include <demo/addTwoNumRequest.h>
#include <demo/addTwoNumResponse.h>


namespace demo
{

struct addTwoNum
{

typedef addTwoNumRequest Request;
typedef addTwoNumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct addTwoNum
} // namespace demo


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::demo::addTwoNum > {
  static const char* value()
  {
    return "210a18f816d5b88becb133b82fae0c4c";
  }

  static const char* value(const ::demo::addTwoNum&) { return value(); }
};

template<>
struct DataType< ::demo::addTwoNum > {
  static const char* value()
  {
    return "demo/addTwoNum";
  }

  static const char* value(const ::demo::addTwoNum&) { return value(); }
};


// service_traits::MD5Sum< ::demo::addTwoNumRequest> should match 
// service_traits::MD5Sum< ::demo::addTwoNum > 
template<>
struct MD5Sum< ::demo::addTwoNumRequest>
{
  static const char* value()
  {
    return MD5Sum< ::demo::addTwoNum >::value();
  }
  static const char* value(const ::demo::addTwoNumRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo::addTwoNumRequest> should match 
// service_traits::DataType< ::demo::addTwoNum > 
template<>
struct DataType< ::demo::addTwoNumRequest>
{
  static const char* value()
  {
    return DataType< ::demo::addTwoNum >::value();
  }
  static const char* value(const ::demo::addTwoNumRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::demo::addTwoNumResponse> should match 
// service_traits::MD5Sum< ::demo::addTwoNum > 
template<>
struct MD5Sum< ::demo::addTwoNumResponse>
{
  static const char* value()
  {
    return MD5Sum< ::demo::addTwoNum >::value();
  }
  static const char* value(const ::demo::addTwoNumResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::demo::addTwoNumResponse> should match 
// service_traits::DataType< ::demo::addTwoNum > 
template<>
struct DataType< ::demo::addTwoNumResponse>
{
  static const char* value()
  {
    return DataType< ::demo::addTwoNum >::value();
  }
  static const char* value(const ::demo::addTwoNumResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEMO_MESSAGE_ADDTWONUM_H
