// Generated by gencpp from file demo/addTwoNumRequest.msg
// DO NOT EDIT!


#ifndef DEMO_MESSAGE_ADDTWONUMREQUEST_H
#define DEMO_MESSAGE_ADDTWONUMREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace demo
{
template <class ContainerAllocator>
struct addTwoNumRequest_
{
  typedef addTwoNumRequest_<ContainerAllocator> Type;

  addTwoNumRequest_()
    : a(0.0)
    , b(0.0)  {
    }
  addTwoNumRequest_(const ContainerAllocator& _alloc)
    : a(0.0)
    , b(0.0)  {
  (void)_alloc;
    }



   typedef float _a_type;
  _a_type a;

   typedef float _b_type;
  _b_type b;




  typedef boost::shared_ptr< ::demo::addTwoNumRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::demo::addTwoNumRequest_<ContainerAllocator> const> ConstPtr;

}; // struct addTwoNumRequest_

typedef ::demo::addTwoNumRequest_<std::allocator<void> > addTwoNumRequest;

typedef boost::shared_ptr< ::demo::addTwoNumRequest > addTwoNumRequestPtr;
typedef boost::shared_ptr< ::demo::addTwoNumRequest const> addTwoNumRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::demo::addTwoNumRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::demo::addTwoNumRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace demo

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::demo::addTwoNumRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::demo::addTwoNumRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo::addTwoNumRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::demo::addTwoNumRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo::addTwoNumRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::demo::addTwoNumRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::demo::addTwoNumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3f6326d24b4937f854196fd3a843f42e";
  }

  static const char* value(const ::demo::addTwoNumRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3f6326d24b4937f8ULL;
  static const uint64_t static_value2 = 0x54196fd3a843f42eULL;
};

template<class ContainerAllocator>
struct DataType< ::demo::addTwoNumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "demo/addTwoNumRequest";
  }

  static const char* value(const ::demo::addTwoNumRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::demo::addTwoNumRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 a\n\
float32 b\n\
";
  }

  static const char* value(const ::demo::addTwoNumRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::demo::addTwoNumRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.b);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct addTwoNumRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::demo::addTwoNumRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::demo::addTwoNumRequest_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<float>::stream(s, indent + "  ", v.a);
    s << indent << "b: ";
    Printer<float>::stream(s, indent + "  ", v.b);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEMO_MESSAGE_ADDTWONUMREQUEST_H
